// ============================================
// USER TYPES
// ============================================

// This is what a User looks like across our entire application
// Both frontend and backend agree on this exact shape
export type User = {
  id: string           // unique identifier, generated by database
  name: string         // full name from their profile
  email: string        // email used to sign up
  createdAt: Date      // when they joined
}

// ============================================
// RESUME TYPES
// ============================================

// One work experience entry from their resume
export type Experience = {
  company: string      // company name
  role: string         // job title
  years: number        // how many years they worked there
  description: string  // what they did there
}

// One project from their resume
export type Project = {
  name: string         // project name
  description: string  // what the project does
  techStack: string[]  // array of technologies used eg: ["React", "Node.js"]
}

// The full parsed resume — AI extracts this from the PDF
export type ParsedResume = {
  skills: string[]           // eg: ["C++", "React", "PostgreSQL"]
  experience: Experience[]   // array of work experiences
  projects: Project[]        // array of projects
  education: {
    college: string
    degree: string
    year: number
  }[]
}

// ============================================
// INTERVIEW TYPES
// ============================================

// What round of interview is happening
// These are the only valid values — no typos possible
export type InterviewRound = "HR" | "TECHNICAL" | "SYSTEM_DESIGN" | "BEHAVIORAL"

// How difficult the current question is
export type DifficultyLevel = "EASY" | "MEDIUM" | "HARD"

// The current state of an interview session
// Think of this like a traffic light — only specific states allowed
export type InterviewStatus =
  | "IDLE"              // not started yet
  | "IN_PROGRESS"       // interview is live
  | "COMPLETED"         // interview finished normally
  | "ABANDONED"         // user left without finishing

// One question asked during an interview
export type InterviewQuestion = {
  id: string
  question: string           // the actual question text
  round: InterviewRound      // which round this belongs to
  difficulty: DifficultyLevel
  expectedThemes: string[]   // what topics a good answer should cover
                             // AI uses this to evaluate the answer
}

// One answer given by the user
export type InterviewAnswer = {
  id: string
  questionId: string         // which question this answers
  answerText: string         // what the user said/typed
  answeredViaVoice: boolean  // true if spoken, false if typed
}

// AI evaluation of one answer
export type AnswerEvaluation = {
  score: number              // 1-10 overall score
  clarity: number            // how clearly they communicated (1-10)
  correctness: number        // how technically correct they were (1-10)
  strengths: string[]        // what they did well
  weaknesses: string[]       // what they missed
  betterAnswerHint: string   // one tip to improve this answer
}

// A complete interview session
export type InterviewSession = {
  id: string
  userId: string             // who is being interviewed
  status: InterviewStatus
  currentRound: InterviewRound
  difficultyLevel: DifficultyLevel
  questions: InterviewQuestion[]
  answers: InterviewAnswer[]
  evaluations: AnswerEvaluation[]
  startedAt: Date
  completedAt: Date | null   // null if not finished yet
}